src/objects/Grocery_Item__c.object
<CustomObject>
    <fields>
        <fullName>Store_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store Section</label>
        <referenceTo>Store_Section__c</referenceTo>
        <relationshipLabel>Grocery Items</relationshipLabel>
        <relationshipName>Grocery_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grocery Item</label>
    <nameField>
        <label>Grocery Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_List__c.object
<CustomObject>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done?</label>
        <type>Checkbox</type>
    </fields>
    <label>Shopping List</label>
    <nameField>
        <label>Shopping List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shopping Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_List_Item__c.object
<CustomObject>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Shopping List Items</relationshipLabel>
        <relationshipName>Shopping_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shopping_List__c</fullName>
        <label>Shopping List</label>
        <referenceTo>Shopping_List__c</referenceTo>
        <relationshipLabel>Shopping List Items</relationshipLabel>
        <relationshipName>Shopping_List_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Shopping List Item</label>
    <nameField>
        <displayFormat>SLI-{0000}</displayFormat>
        <label>Shopping List Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store_Section__c.object
<CustomObject>
    <label>Store Section</label>
    <nameField>
        <label>Store Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/shoppingListControllerTest.cls
@isTest
private class shoppingListControllerTest {

    @testSetup static void methodName() {
        Store_Section__c ss             = new Store_Section__c(Name = 'Store Section');
        insert ss;
        Grocery_Item__c gi      = new Grocery_Item__c(Name ='Grocery', Store_Section__c = ss.Id);
        insert gi;

        Recipe__c r         = new Recipe__c(Name = 'Recipe');
        insert r; 

        Ingredient__c i     = new Ingredient__c(Recipe__c = r.Id, Grocery_Item__c = gi.Id);
        insert i;

        Shopping_List__c sl = new Shopping_List__c();
        insert sl;

    }
	
	@isTest static void itemTest() {
		Shopping_List__c sl = [select Id from Shopping_List__c where Done__c = false limit 1];
        Grocery_Item__c gi     = [select Id, Name from Grocery_Item__c where Name = 'Grocery'];
        Store_Section__c ss     = [select Id, Name from Store_Section__c where Name = 'Store Section'];
        Recipe__c r     = [select Id, Name from Recipe__c where Name = 'Recipe'];

        System.assert(shoppingListController.addItem(sl.Id, gi.Name, ss.Name));

        Shopping_List_Item__c sli   = [select Id from Shopping_List_Item__c where Shopping_list__c = :sl.Id];

        System.assert(shoppingListController.markItemDone(sli.Id));

        System.assert(shoppingListController.removeItem(sli.Id));

        System.assert(shoppingListController.addItem(sl.Id, gi.Name, ss.Name));

        List<Shopping_List_Item__c> slList     = shoppingListController.returnShoppingListBySection(sl.Id);
        System.assertEquals(slList.size(), 1);

        sl.Done__c      = true;
        update sl;

        Shopping_List__c sl2    = new Shopping_List__c();
        insert sl2;

        System.assert(shoppingListController.addItemsFromPreviousTrip(sl2.Id));

        List<Shopping_List_Item__c> sl2List     = shoppingListController.returnShoppingListBySection(sl2.Id);
        System.assertEquals(sl2List.size(), 1);

	}
	

    @isTest static void searchTest() {
        List<Recipe__c> rList   = shoppingListController.searchRecipes('Reci');
        System.assertEquals(rList.size(), 1);
    }

	
}