src/objects/Grocery_Item__c.object
<CustomObject>
    <fields>
        <fullName>Store_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store Section</label>
        <referenceTo>Store_Section__c</referenceTo>
        <relationshipLabel>Grocery Items</relationshipLabel>
        <relationshipName>Grocery_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grocery Item</label>
    <nameField>
        <label>Grocery Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_List__c.object
<CustomObject>
    <label>Shopping List</label>
    <nameField>
        <label>Shopping List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shopping Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Store_Section__c.object
<CustomObject>
    <label>Store Section</label>
    <nameField>
        <label>Store Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/groceryUtilsTests.cls
@isTest
private class groceryUtilsTests {
    @testSetup static void methodName() {
        Store_Section__c ss             = new Store_Section__c(Name = 'Store Section');
        insert ss;
        Grocery_Item__c gi      = new Grocery_Item__c(Name ='Grocery', Store_Section__c = ss.Id);
        insert gi;

        Recipe__c r         = new Recipe__c(Name = 'Recipe');
        insert r; 

        Ingredient__c i     = new Ingredient__c(Recipe__c = r.Id, Grocery_Item__c = gi.Id);
        insert i;
    }

	
	@isTest static void getGroceryItemByNameAndSectionTest() {
		Grocery_Item__c gi = groceryUtils.getGroceryItemByNameAndSection('Grocery', 'Store Section');
        System.assertNotEquals(gi, null);
        System.assertNotEquals(gi.Id, null);

        Grocery_Item__c gi2 = groceryUtils.getGroceryItemByNameAndSection('New Grocery Item', 'Store Section');
        System.assertNotEquals(gi2, null);
        System.assertNotEquals(gi2.Id, null);
	}
	
	@isTest static void getGroceryItemByNameTest() {
        Store_Section__c ss     = [select Id from Store_Section__c where Name = 'Store Section'];
        Grocery_Item__c gi = groceryUtils.getGroceryItemByName('Grocery', ss);
        System.assertNotEquals(gi, null);
        System.assertNotEquals(gi.Id, null);
	}


    @isTest static void getStoreSectionByNameTest() {
        Store_Section__c ss = groceryUtils.getStoreSectionByName('Store Section');
        System.assertNotEquals(ss, null);
        System.assertNotEquals(ss.Id, null);

        Store_Section__c ss2 = groceryUtils.getStoreSectionByName('New Section');
        System.assertNotEquals(ss2, null);
        System.assertNotEquals(ss2.Id, null);
    }


    @isTest static void returnRecipeIngredientsTest() {
        Recipe__c r         = [select Id from Recipe__c where Name = 'Recipe'];
        List<Ingredient__c> iList = groceryUtils.returnRecipeIngredients(r.Id);
        System.assertNotEquals(iList.size(), 0);
    }


    @isTest static void addRecipeToShoppingListByIdTest() {
        Recipe__c r         = [select Id from Recipe__c where Name = 'Recipe'];
        Shopping_List__c sl = new Shopping_List__c();
        insert sl;

        System.assert(groceryUtils.addRecipeToShoppingListById(r.Id, sl.Id));
    }

    @isTest static void addRecipeToRecentShoppingListTest() {
        Recipe__c r         = [select Id from Recipe__c where Name = 'Recipe'];
        Shopping_List__c sl = new Shopping_List__c();
        insert sl;

        System.assert(groceryUtils.addRecipeToRecentShoppingList(r.Id));
    }

    @isTest static void getActiveShoppingListIdTest() {
        System.assertNotEquals(groceryUtils.getActiveShoppingListId(), null);
    }

}