src/objects/Grocery_Item__c.object
<CustomObject>
    <fields>
        <fullName>Store_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store Section</label>
        <referenceTo>Store_Section__c</referenceTo>
        <relationshipLabel>Grocery Items</relationshipLabel>
        <relationshipName>Grocery_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grocery Item</label>
    <nameField>
        <label>Grocery Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Store_Section__c.object
<CustomObject>
    <label>Store Section</label>
    <nameField>
        <label>Store Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/groceryItemAutoCompleteTests.cls
@isTest
private class groceryItemAutoCompleteTests {

    @testSetup static void methodName() {
        Store_Section__c ss             = new Store_Section__c(Name = 'Store Section');
        insert ss;
        Grocery_Item__c gi      = new Grocery_Item__c(Name ='Grocery', Store_Section__c = ss.Id);
        insert gi;
    }	

	@isTest static void searchGroceryItemsTest() {
		System.assertEquals(groceryItemAutoComplete.searchGroceryItems('Grocery').size(), 1);
        System.assertEquals(groceryItemAutoComplete.searchGroceryItems('Blah').size(), 0);
	}
	
	@isTest static void searchStoreSectionTest() {
        System.assertEquals(groceryItemAutoComplete.searchStoreSection('Store').size(), 1);
        System.assertEquals(groceryItemAutoComplete.searchStoreSection('Blah').size(), 0);
	}
	
}