src/objects/Grocery_Item__c.object
<CustomObject>
    <fields>
        <fullName>Store_Section__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store Section</label>
        <referenceTo>Store_Section__c</referenceTo>
        <relationshipLabel>Grocery Items</relationshipLabel>
        <relationshipName>Grocery_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grocery Item</label>
    <nameField>
        <label>Grocery Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_List__c.object
<CustomObject>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done?</label>
        <type>Checkbox</type>
    </fields>
    <label>Shopping List</label>
    <nameField>
        <label>Shopping List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shopping Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shopping_List_Item__c.object
<CustomObject>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Shopping List Items</relationshipLabel>
        <relationshipName>Shopping_List_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shopping_List__c</fullName>
        <label>Shopping List</label>
        <referenceTo>Shopping_List__c</referenceTo>
        <relationshipLabel>Shopping List Items</relationshipLabel>
        <relationshipName>Shopping_List_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Shopping List Item</label>
    <nameField>
        <displayFormat>SLI-{0000}</displayFormat>
        <label>Shopping List Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shopping List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Store_Section__c.object
<CustomObject>
    <label>Store Section</label>
    <nameField>
        <label>Store Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/groceryUtils.cls
public with sharing class groceryUtils {

    /* ==================================================================
    SEARCHING / CREATING GROCERY ITEMS
    =====================================================================*/
        public static Grocery_Item__c getGroceryItemByNameAndSection(String groceryName, String storeSection) {
            Store_Section__c s      = groceryUtils.getStoreSectionByName(storeSection);
            return groceryUtils.getGroceryItemByName(groceryName, s);
        }


        public static Grocery_Item__c getGroceryItemByName(String groceryName, Store_Section__c s) {
            List<Grocery_Item__c> giList    = [select Id, Name, Store_Section__c from Grocery_Item__c where Name = :groceryName AND Store_Section__c = :s.Id];
            if(!giList.isEmpty())
                return giList[0];
            Grocery_Item__c gi      = new Grocery_Item__c(Name = groceryName, Store_Section__c = s.Id);
            insert gi;
            return gi;
        }





    /* ==================================================================
    SEARCHING / CREATING STORE SECTIONS
    =====================================================================*/
        public static Store_Section__c getStoreSectionByName(String storeSection) {
            List<Store_Section__c> ssList   = [select Id, Name from Store_Section__c where Name = :storeSection];
            if(!ssList.isEmpty())
                return ssList[0];
            Store_Section__c ss             = new Store_Section__c(Name = storeSection);
            insert ss;
            return ss;
        }




    /* ==================================================================
    RECIPE INGREDIENTS
    =====================================================================*/
        public static List<Ingredient__c> returnRecipeIngredients(String recipeId) {
            return [SELECT Id, Name, Grocery_Item__c, Grocery_Item__r.Name, Grocery_Item__r.Store_Section__r.Name FROM Ingredient__c where Recipe__c = :recipeId ORDER BY Name];
        }


        public static Boolean addRecipeToShoppingListById(String recipeId, String shoppingListId) {
            System.debug('recipeId = ' + recipeId);
            System.debug('shoppingListId = ' + shoppingListId);
            List<Shopping_List_Item__c> sliList     = new List<Shopping_List_Item__c>();
            for(Ingredient__c i : groceryUtils.returnRecipeIngredients(recipeId))
                sliList.add(new Shopping_List_Item__c(Shopping_List__c = shoppingListId, Grocery_Item__c = i.Grocery_Item__c));
            System.debug('sliList = ' + sliList);
            try {
                insert sliList;
            } catch(DmlException e) {
                return false;
            }
            return true;
        }


        public static Boolean addRecipeToRecentShoppingList(String recipeId) {
            return addRecipeToShoppingListById(recipeId, groceryUtils.getActiveShoppingListId());
        }



    public static Id getActiveShoppingListId() {
        List<Shopping_List__c> slList   = [select Id from Shopping_List__c where Done__c = false order by CreatedDate desc limit 1];
        if(slList.isEmpty()) {
            Shopping_List__c sl     = new Shopping_List__c();
            insert sl;
            slList.add(sl);
        }
        return slList[0].Id;
    }
}