src/objects/Grocery_Item__c.object
<CustomObject>
    <label>Grocery Item</label>
    <nameField>
        <label>Grocery Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grocery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ingredient__c.object
<CustomObject>
    <fields>
        <fullName>Grocery_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Grocery Item</label>
        <referenceTo>Grocery_Item__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipe__c</fullName>
        <label>Recipe</label>
        <referenceTo>Recipe__c</referenceTo>
        <relationshipLabel>Ingredients</relationshipLabel>
        <relationshipName>Ingredients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Ingredient</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Ingredient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/recipeController.cls
public with sharing class recipeController {


    @AuraEnabled
    public static Boolean addIngredient(String recipeId, String groceryItemName, String storeSectionName) {
        Grocery_Item__c gi  = groceryUtils.getGroceryItemByNameAndSection(groceryItemName, storeSectionName);

        Ingredient__c i     = new Ingredient__c(Recipe__c = recipeId, Grocery_Item__c = gi.Id);
        try {
            insert i;
        } catch (DmlException e) {
            return false;
        }
        return true;
    }


    @AuraEnabled
    public static Boolean removeIngredient(String ingredientId) {
        Ingredient__c i     = new Ingredient__c(Id = ingredientId);
        try {
            delete i;
        } catch (DmlException e) {
            return false;
        }
        return true;
    }



    @AuraEnabled
    public static List<Ingredient__c> getIngredients(String recipeId) {
        System.debug('recipeId = ' + recipeId);
        return groceryUtils.returnRecipeIngredients(recipeId);
    }


    @AuraEnabled 
    public static Boolean addRecipeToShoppingList(String recipeId) {
        return groceryUtils.addRecipeToRecentShoppingList(recipeId);
    }


    @AuraEnabled 
    public static Id getShoppingListId() {
        return groceryUtils.getActiveShoppingListId();
    }

}